name: DJ FUGLY
favicon: null
layout_spectrum: 1
typography_spectrum: 0.21321
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#81b400'
    - '#00cf3a'
    - '#ffffff'
    - '#364b00'
  brandStrength: 0.5
  lightness: 0
  saturation: 0.5
  rhythmicContrast: 1
purpose: []
